// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WineCellar.Entities;

namespace WineCellar.Migrations
{
    [DbContext(typeof(WineCellarDBContext))]
    [Migration("20201111214223_CreateWineTable")]
    partial class CreateWineTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WineCellar.Entities.BottleSizeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BottleSize")
                        .HasColumnType("text");

                    b.Property<bool>("Default")
                        .HasColumnType("boolean");

                    b.Property<string>("Volume")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BottleSizes");
                });

            modelBuilder.Entity("WineCellar.Entities.VarietalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Varietal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Varietals");
                });

            modelBuilder.Entity("WineCellar.Entities.WineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BottleSizeEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("BottlesDrank")
                        .HasColumnType("integer");

                    b.Property<int>("BottlesPurchased")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("VarietalEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Vintage")
                        .HasColumnType("text");

                    b.Property<string>("WhenPurchased")
                        .HasColumnType("text");

                    b.Property<int>("WineryEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BottleSizeEntityId");

                    b.HasIndex("VarietalEntityId");

                    b.HasIndex("WineryEntityId");

                    b.ToTable("Wines");
                });

            modelBuilder.Entity("WineCellar.Entities.WineryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EMail")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("WebSite")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Wineries");
                });

            modelBuilder.Entity("WineCellar.Entities.WineEntity", b =>
                {
                    b.HasOne("WineCellar.Entities.BottleSizeEntity", "BottleSize")
                        .WithMany()
                        .HasForeignKey("BottleSizeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WineCellar.Entities.VarietalEntity", "Varietal")
                        .WithMany()
                        .HasForeignKey("VarietalEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WineCellar.Entities.WineryEntity", "Winery")
                        .WithMany()
                        .HasForeignKey("WineryEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
